import { ProductPreview } from "@/src/entities/product";
import { Paginated } from "@/src/features/pagination";

export const getProductsApi = async (
  usp: URLSearchParams
): Promise<Paginated<ProductPreview>> => {
  return {
    count: 8,
    next: undefined,
    previous: undefined,
    pages: 1,
    results: [
      {
        id: 1,
        type: "СЫВОРОТКА ДЛЯ ЛИЦА",
        slug: "slug1",
        name: "MA:NYO bifida biome complex ampoule",
        stock: true,
        price: 3000,
        discount: 20,
        img: "/__dump/images/product.png",
      },
      {
        id: 2,
        type: "СЫВОРОТКА ДЛЯ ЛИЦА",
        slug: "slug2",
        name: "MA:NYO bifida biome complex ampoule",
        stock: true,
        price: 3000,
        discount: 20,
        img: "/__dump/images/product.png",
      },
      {
        id: 3,
        type: "СЫВОРОТКА ДЛЯ ЛИЦА",
        slug: "slug3",
        name: "MA:NYO bifida biome complex ampoule",
        stock: true,
        price: 3000,
        discount: 20,
        img: "/__dump/images/product.png",
      },
      {
        id: 4,
        type: "СЫВОРОТКА ДЛЯ ЛИЦА",
        slug: "slug4",
        name: "MA:NYO bifida biome complex ampoule",
        stock: true,
        price: 3000,
        discount: 20,
        img: "/__dump/images/product.png",
      },
      {
        id: 5,
        type: "СЫВОРОТКА ДЛЯ ЛИЦА",
        slug: "slug5",
        name: "MA:NYO bifida biome complex ampoule",
        stock: true,
        price: 3000,
        discount: 20,
        img: "/__dump/images/product.png",
      },
      {
        id: 6,
        type: "СЫВОРОТКА ДЛЯ ЛИЦА",
        slug: "slug6",
        name: "MA:NYO bifida biome complex ampoule",
        stock: true,
        price: 3000,
        discount: 20,
        img: "/__dump/images/product.png",
      },
      {
        id: 7,
        type: "СЫВОРОТКА ДЛЯ ЛИЦА",
        slug: "slug7",
        name: "MA:NYO bifida biome complex ampoule",
        stock: true,
        price: 3000,
        discount: 20,
        img: "/__dump/images/product.png",
      },
      {
        id: 8,
        type: "СЫВОРОТКА ДЛЯ ЛИЦА",
        slug: "slug8",
        name: "MA:NYO bifida biome complex ampoule",
        stock: true,
        price: 3000,
        discount: 20,
        img: "/__dump/images/product.png",
      },
    ],
  };
};
