import type { Metadata } from "next";
import { fonts } from "@/src/app/fonts";
import "@/src/app/styles/index.scss";
import { NextIntlClientProvider } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;
  return (
    <html lang={locale}>
      <body className={fonts.variable}>
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
      </body>
    </html>
  );
}
