import type { Metadata } from "next";
import { fonts } from "@/src/app/fonts";
import "@/src/app/styles/index.scss";
import { NextIntlClientProvider } from "next-intl";
import { Header } from "@/src/widgets/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  params,
  children,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;
  return (
    <html lang={locale}>
      <body className={fonts.variable}>
        <NextIntlClientProvider>
          <Header />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
